### ISSUE TITLE
Example notebook fails to run because of Cholesky decomposition issue

### ISSUE THREAD

**Issue by loswald** [Joshuaalbert/heterogp#2]
Hi,
I ran the example notebook and the HGP model bugs out at the run_with_adam step, apparently due to the Cholesky decomposition not working. Can you please look into this?

```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/Anaconda/Install/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1360     try:
-> 1361       return fn(*args)
   1362     except errors.OpError as e:

/Anaconda/Install/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run_fn(session, feed_dict, fetch_list, target_list, options, run_metadata)
   1339           return tf_session.TF_Run(session, options, feed_dict, fetch_list,
-> 1340                                    target_list, status, run_metadata)
   1341 

/Anaconda/Install/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    515             compat.as_text(c_api.TF_Message(self.status.status)),
--> 516             c_api.TF_GetCode(self.status.status))
    517     # Delete the underlying status object from memory otherwise it stays alive

InvalidArgumentError: Cholesky decomposition was not successful. The input might not be valid.
	 [[Node: HGP-f08fd6a7-39/Cholesky = Cholesky[T=DT_DOUBLE, _device="/job:localhost/replica:0/task:0/device:CPU:0"](HGP-f08fd6a7-39/add_1)]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-5-f06685338f2d> in <module>
     31     from timeit import default_timer
     32     t0 = default_timer()
---> 33     run_with_adam(model,1e-3,iterations,PrintAction(model,"Adam"))
     34     print(default_timer() - t0)
     35     # Predictions uses stochastic sampling and produces

<ipython-input-2-ef873c1dff04> in run_with_adam(model, lr, iterations, callback)
     19     actions = actions if callback is None else actions + [callback]
     20 
---> 21     Loop(actions, stop=iterations)()
     22     model.anchor(model.enquire_session())

/Anaconda/Install/lib/python3.6/site-packages/gpflow/actions.py in __call__(self, context)
    142         try:
    143             self.watcher.start()
--> 144             self.run(context)
    145         finally:
    146             self.watcher.stop()

/Anaconda/Install/lib/python3.6/site-packages/gpflow/actions.py in run(self, context)
    239                 break
    240             try:
--> 241                 self._action(context)
    242             except Loop.Continue:
    243                 continue

/Anaconda/Install/lib/python3.6/site-packages/gpflow/actions.py in __call__(self, context)
    142         try:
    143             self.watcher.start()
--> 144             self.run(context)
    145         finally:
    146             self.watcher.stop()

/Anaconda/Install/lib/python3.6/site-packages/gpflow/actions.py in run(self, context)
    262         """
    263         for action in self._actions:
--> 264             action(context)
    265 
    266 

/Anaconda/Install/lib/python3.6/site-packages/gpflow/actions.py in __call__(self, context)
    142         try:
    143             self.watcher.start()
--> 144             self.run(context)
    145         finally:
    146             self.watcher.stop()

/Anaconda/Install/lib/python3.6/site-packages/gpflow/actions.py in run(self, context)
    364 
    365     def run(self, context: ActionContext) -> None:
--> 366         context.session.run(self.optimizer_tensor, **self.run_kwargs)
    367 
    368 

/Anaconda/Install/lib/python3.6/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    903     try:
    904       result = self._run(None, fetches, feed_dict, options_ptr,
--> 905                          run_metadata_ptr)
    906       if run_metadata:
    907         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/Anaconda/Install/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1135     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1136       results = self._do_run(handle, final_targets, final_fetches,
-> 1137                              feed_dict_tensor, options, run_metadata)
   1138     else:
   1139       results = []

/Anaconda/Install/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1353     if handle is None:
   1354       return self._do_call(_run_fn, self._session, feeds, fetches, targets,
-> 1355                            options, run_metadata)
   1356     else:
   1357       return self._do_call(_prun_fn, self._session, handle, feeds, fetches)

/Anaconda/Install/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1372         except KeyError:
   1373           pass
-> 1374       raise type(e)(node_def, op, message)
   1375 
   1376   def _extend_graph(self):

InvalidArgumentError: Cholesky decomposition was not successful. The input might not be valid.
	 [[Node: HGP-f08fd6a7-39/Cholesky = Cholesky[T=DT_DOUBLE, _device="/job:localhost/replica:0/task:0/device:CPU:0"](HGP-f08fd6a7-39/add_1)]]

Caused by op 'HGP-f08fd6a7-39/Cholesky', defined at:
  File "/Anaconda/Install/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Anaconda/Install/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Anaconda/Install/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Anaconda/Install/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Anaconda/Install/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/Anaconda/Install/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/Anaconda/Install/lib/python3.6/asyncio/base_events.py", line 422, in run_forever
    self._run_once()
  File "/Anaconda/Install/lib/python3.6/asyncio/base_events.py", line 1434, in _run_once
    handle._run()
  File "/Anaconda/Install/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/Anaconda/Install/lib/python3.6/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/Anaconda/Install/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/Anaconda/Install/lib/python3.6/site-packages/tornado/gen.py", line 1233, in inner
    self.run()
  File "/Anaconda/Install/lib/python3.6/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/Anaconda/Install/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/Anaconda/Install/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/Anaconda/Install/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Anaconda/Install/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/Anaconda/Install/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/Anaconda/Install/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/Anaconda/Install/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Anaconda/Install/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Anaconda/Install/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2819, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/Anaconda/Install/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2845, in _run_cell
    return runner(coro)
  File "/Anaconda/Install/lib/python3.6/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/Anaconda/Install/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3020, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Anaconda/Install/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3185, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/Anaconda/Install/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-f06685338f2d>", line 30, in <module>
    model.compile()
  File "/Anaconda/Install/lib/python3.6/site-packages/gpflow/core/node.py", line 58, in compile
    self.build()
  File "/Anaconda/Install/lib/python3.6/site-packages/gpflow/core/node.py", line 156, in build
    self._build()
  File "/Anaconda/Install/lib/python3.6/site-packages/gpflow/models/model.py", line 79, in _build
    likelihood = self._build_likelihood()
  File "/Anaconda/Install/lib/python3.6/site-packages/gpflow/decors.py", line 67, in tensor_mode_wrapper
    result = method(obj, *args, **kwargs)
  File "/Anaconda/Install/lib/python3.6/site-packages/heterogp/hgp.py", line 90, in _build_likelihood
    L = tf.reduce_sum(self.E_log_p_Y(self.X, self.Y))
  File "/Anaconda/Install/lib/python3.6/site-packages/heterogp/hgp.py", line 73, in E_log_p_Y
    hetero_variance = tf.square(self.likelihood.hetero_noise(X))
  File "/Anaconda/Install/lib/python3.6/site-packages/gpflow/decors.py", line 67, in tensor_mode_wrapper
    result = method(obj, *args, **kwargs)
  File "/Anaconda/Install/lib/python3.6/site-packages/heterogp/likelihoods.py", line 55, in hetero_noise
    log_noise,_,_ = self.log_noise_latent.sample_from_conditional(X,full_cov=True)
  File "/Anaconda/Install/lib/python3.6/site-packages/heterogp/latent.py", line 104, in sample_from_conditional
    samples = reparameterize(mean, var, z, full_cov=full_cov)
  File "/Anaconda/Install/lib/python3.6/site-packages/heterogp/latent.py", line 49, in reparameterize
    chol = tf.cholesky(var + I)  # SDNN
  File "/Anaconda/Install/lib/python3.6/site-packages/tensorflow/python/ops/gen_linalg_ops.py", line 412, in cholesky
    "Cholesky", input=input, name=name)
  File "/Anaconda/Install/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Anaconda/Install/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/Anaconda/Install/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cholesky decomposition was not successful. The input might not be valid.
	 [[Node: HGP-f08fd6a7-39/Cholesky = Cholesky[T=DT_DOUBLE, _device="/job:localhost/replica:0/task:0/device:CPU:0"](HGP-f08fd6a7-39/add_1)]]
```

**Comment by ssuraci** [comment]
I confirm the same issue with example data (I reduced minibatch size to 250):

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cholesky decomposition was not successful. The input might not be valid.
         [[{{node HGP-17bd50e8-30/Cholesky}}]]
```

```
Name: gpflow
Version: 1.2.0

Name: tensorflow
Version: 1.7.1
```
